### ISSUE TITLE
add some prefix

### ISSUE THREAD

**Issue by codediy** [nia40m/vscode-display-nums#2]
can you and some prefix ,$C2000 -> hex, %01010-> bin , 65xx asm use this

**Comment by nia40m** [comment]
I have an idea how to do it but need some time for testing and firstly need to remember how to build vscode extensions to try it :-/

Also, I think it should be an optional feature because symbol '%' is used a lot as modulo and the code like `a%10` can make the plugin interpret the number wrongly.

**Comment by nia40m** [comment]
Added support for 65xx asm notation only when hovering such numbers with this commit 5dd996f
