### ISSUE TITLE
Not working since 0.3.0

### ISSUE THREAD

**Issue by rcmz** [nia40m/vscode-display-nums#3]
Hello,

The extension is not working for me since the last update (0.3.0   6/12/2023)
Nothing appends when I hover my mouse over a number.
It was working without issue before.

I'm using Visual Studio Code 1.79.2 on Ubuntu 22.04

**Comment by nia40m** [comment]
Just tried it with VS Code 1.79.2 on Linux Mint 21.1 that is based on Ubuntu 22.04 and the plugin seems to work fine
Will try to install Ubuntu on Virtualbox to check it there

@rcmz 
In the meantime, do you have any other suggestions, what else could be wrong?
Maybe another plugin is interfering with mine? Can you list yours or even disable to check? (if there is no so much of them)

**Comment by rcmz** [comment]
I tried disabling all other extensions, using a different profile, opening a different folder, and still nothing

**Comment by nia40m** [comment]
Found a problem with a regular expression I use to select hovered numbers
Just pushed a new 0.3.1 version
Can you, @rcmz, update and try if it fixes your issue?

**Comment by rcmz** [comment]
The update fixed it 🙂
Thanks for maintaining this awesome extension

**Comment by nia40m** [comment]
Fixed with 4efa1c3
