### ISSUE TITLE
Not working correctly with large numbers

### ISSUE THREAD

**Issue by MohamedYKamal** [nia40m/vscode-display-nums#4]
Bit representation of large numbers is not correct, here I am using a 64 bit number, and it discards the reading of first 3 bytes, same happens with larger numbers with more discarded bytes
![image](https://github.com/nia40m/vscode-display-nums/assets/14422683/ee0aad11-6fc9-4e4e-91b6-885b9554b9a5)

**Comment by nia40m** [comment]
Thank you for raising this issue
I'll try to find a solution for this problem

**Comment by nia40m** [comment]
Fixed the issue in new plugin version 0.3.2 (https://github.com/nia40m/vscode-display-nums/commit/54832c016f24b0f15f0afef339410fec5a092473)
It is already available in the store so please test it when you can @MohamedYKamal 

p.s. sorry for such a late update
